### ISSUE TITLE
Generalize the training function to accept any kind of model

### ISSUE THREAD

**Issue by edwinb-ai** [DCI-NET/segnet#14]
The following line is part of the `train/unet.py` module within `segnet` that makes it easier and faster to train a UNet-like model.
https://github.com/DCI-NET/segnet/blob/b8385bb6b9ec3c352c1ed9d17f453b1d659b4141/segnet/train/unet.py#L47
Although this is intended behavior, it should be quite simple to make it general, i.e. to accept a parameter from the function call that can accept _any_ kind of `tf.keras.Model` instance.

**Comment by edwinb-ai** [comment]
@gmagannaDevelop Do you mind working on this? This should make it even easier to train any model within `segnet`.

**Comment by gmagannaDevelop** [comment]
I'd love to! I'm checking the code in order to better understand the function's behaviour. I'll start working on in on my fork right away!
